#!/bin/sh

datestamp=$(date +%Y_%m_%d)

memorystick="/Volumes/cam"

if [ -d $memorystick ];then
    echo ""
      printf '\e[36m'
    echo "|-+-+-+-+-+-+-+-+-+-+-+-|"
      # printf '\e[36m'
    echo "|        PHOTODUMP      |"
      # printf '\e[34m'
    echo "|-+-+-+-+-+-+-+-+-+-+-+-|"
    echo ""
      printf '\e[31m'
    echo "Here's the folders on the memory stick:"  
      printf '\e[32m'

    dirs=(/Volumes/CAM/DCIM/*)

    read -p "$(
          f=0
          for dirname in "${dirs[@]}" ; do
                  echo "$((++f)): $dirname"
          done

          echo 'Please select the folder to photodump: '
    )" selection

    selected_dir="${dirs[$((selection-1))]}"

    echo "You picked: '$selected_dir'"
    echo ""

      printf '\e[31m'
    echo "What do you want to call today's folder? (one word please)"  
      printf '\e[32m'
    read name
      printf '\e[m'
    foldername=$datestamp
    foldername+="-"
    foldername+=$name
    # echo $foldername
    echo ""
    printf '\e[34m'
    echo "- - - - - - - - - - - - - - - - - -"
    # printf '\e[36m'
    # echo "Here's what's on the memory stick:"
      printf '\e[35m'
    echo "Selected contents:"
    # get number of files
    filenumber=$(ls -1 $selected_dir | wc -l)
    echo "Folder has" $filenumber "files."
    du -sh $selected_dir;
    printf '\e[34m'
    echo "- - - - - - - - - - - - - - - - - -"
    echo ""
    if [ -e ~/Pictures/$foldername ];then 
        printf '\e[31m'
    echo "Wait a minute! It looks like you're about to overwrite a folder."      
    echo "Try renaming today's earlier folder and running videodump again."
        printf '\e[m'
    else
        printf '\e[36m'
      echo "Ok, I'm going to wipe the memory stick clean,"
      echo "and move everything to a folder named:"
         printf '\e[m'
      echo $foldername
         printf '\e[31m'
      echo ""   
      echo "Continue? (y/n)"
         printf '\e[32m'
      read choice
         printf '\e[31m'
      case "$choice" in 
        y|Y ) 
         echo "Got it."
         echo ""
         printf '\e[m'
          # main meat of the script
              printf '\e[36m'
          echo "Making the folder in your Pictures directory:"
              printf '\e[m'
          mkdir ~/Pictures/$foldername
          echo "/Pictures/$foldername"
              printf '\e[36m'
          echo ""
              printf '\e[35m'
          echo "Now, just chill while I move the files..."
              printf '\e[m'
          cp -v $selected_dir/*.* ~/Pictures/$foldername
          rm $selected_dir/*.*
              printf '\e[32m'
          echo "Done! Onward."
          echo ""
              printf '\e[m'
          open ~/Pictures/$foldername
          
          # end case
          ;;

        n|N ) 
          echo "Alright, exiting for now."
          echo ""

          # end case
          ;;
        
        * ) echo "invalid";;
      esac
    fi
 else printf '\e[31m' 
      echo "I can't find the memory stick I'm looking for."
      printf '\e[m'
fi


